/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author agust
 */
public class PanelSeleccionAciento extends javax.swing.JFrame {

    /**
     * Creates new form PanelSeleccionAciento
     */
    public PanelSeleccionAciento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        jButton102 = new javax.swing.JButton();
        jButton103 = new javax.swing.JButton();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton106 = new javax.swing.JButton();
        jButton107 = new javax.swing.JButton();
        jButton108 = new javax.swing.JButton();
        jButton109 = new javax.swing.JButton();
        jButton110 = new javax.swing.JButton();
        jButton111 = new javax.swing.JButton();
        jButton112 = new javax.swing.JButton();
        jButton113 = new javax.swing.JButton();
        jButton114 = new javax.swing.JButton();
        jButton115 = new javax.swing.JButton();
        jButton116 = new javax.swing.JButton();
        jButton117 = new javax.swing.JButton();
        jButton118 = new javax.swing.JButton();
        jButton119 = new javax.swing.JButton();
        jButton120 = new javax.swing.JButton();
        jButton121 = new javax.swing.JButton();
        jButton122 = new javax.swing.JButton();
        jButton123 = new javax.swing.JButton();
        jButton124 = new javax.swing.JButton();
        jButton125 = new javax.swing.JButton();
        jButton126 = new javax.swing.JButton();
        jButton127 = new javax.swing.JButton();
        jButton128 = new javax.swing.JButton();
        jButton129 = new javax.swing.JButton();
        jButton130 = new javax.swing.JButton();
        jButton131 = new javax.swing.JButton();
        jButton132 = new javax.swing.JButton();
        jButton133 = new javax.swing.JButton();
        jButton134 = new javax.swing.JButton();
        jButton135 = new javax.swing.JButton();
        jButton136 = new javax.swing.JButton();
        jButton137 = new javax.swing.JButton();
        jButton138 = new javax.swing.JButton();
        jButton139 = new javax.swing.JButton();
        jButton140 = new javax.swing.JButton();
        jButton141 = new javax.swing.JButton();
        jButton142 = new javax.swing.JButton();
        jButton143 = new javax.swing.JButton();
        jButton144 = new javax.swing.JButton();
        jButton145 = new javax.swing.JButton();
        jButton146 = new javax.swing.JButton();
        jButton147 = new javax.swing.JButton();
        jButton148 = new javax.swing.JButton();
        jButton149 = new javax.swing.JButton();
        jButton150 = new javax.swing.JButton();
        jButton151 = new javax.swing.JButton();
        jButton152 = new javax.swing.JButton();
        jButton153 = new javax.swing.JButton();
        jButton154 = new javax.swing.JButton();
        jButton155 = new javax.swing.JButton();
        jButton156 = new javax.swing.JButton();
        jButton157 = new javax.swing.JButton();
        jButton158 = new javax.swing.JButton();
        jButton159 = new javax.swing.JButton();
        jButton160 = new javax.swing.JButton();
        jButton161 = new javax.swing.JButton();
        jButton162 = new javax.swing.JButton();
        jButton163 = new javax.swing.JButton();
        jButton164 = new javax.swing.JButton();
        jButton165 = new javax.swing.JButton();
        jButton166 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 290, 20, 20));
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 270, 20, 20));
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, 20, 20));
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 20, 20));
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 20, 20));
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 20, 20));
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 20, 20));
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 290, 20, 20));
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 20, 20));
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 20, 20));
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 20, 20));
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 20, 20));
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 20, 20));
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 20, 20));
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 20, 20));
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 20, 20));
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 190, 20, 20));
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 210, 20, 20));
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 20, 20));
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 20, 20));
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 20, 20));
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 20, 20));
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 20, 20));
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 20, 20));
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 20, 20));
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 20, 20));
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 20, 20));
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 20, 20));
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 20, 20));
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 20, 20));
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 20, 20));
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 20, 20));
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 20, 20));
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 20, 20));
        getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 20, 20));
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 20, 20));
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 20, 20));
        getContentPane().add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 20, 20));
        getContentPane().add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 20, 20));
        getContentPane().add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 20, 20));
        getContentPane().add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 20, 20));
        getContentPane().add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 20, 20));
        getContentPane().add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 20, 20));
        getContentPane().add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 20, 20));
        getContentPane().add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 20, 20));
        getContentPane().add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 20, 20));
        getContentPane().add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 20, 20));
        getContentPane().add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 20, 20));
        getContentPane().add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 20, 20));
        getContentPane().add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 20, 20));
        getContentPane().add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 20, 20));
        getContentPane().add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 20, 20));
        getContentPane().add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 20, 20));
        getContentPane().add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 20, 20));
        getContentPane().add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 20, 20));
        getContentPane().add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 20, 20));
        getContentPane().add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 270, 20, 20));
        getContentPane().add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 290, 20, 20));
        getContentPane().add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 130, 20, 20));
        getContentPane().add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 20, 20));
        getContentPane().add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 130, 20, 20));
        getContentPane().add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 150, 20, 20));
        getContentPane().add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 270, 20, 20));
        getContentPane().add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 290, 20, 20));
        getContentPane().add(jButton65, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 20, 20));
        getContentPane().add(jButton66, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 230, 20, 20));
        getContentPane().add(jButton67, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 20, 20));
        getContentPane().add(jButton68, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, 20, 20));
        getContentPane().add(jButton69, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 210, 20, 20));
        getContentPane().add(jButton70, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 230, 20, 20));
        getContentPane().add(jButton71, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 190, 20, 20));
        getContentPane().add(jButton72, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 190, 20, 20));
        getContentPane().add(jButton73, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, 20, 20));
        getContentPane().add(jButton74, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 210, 20, 20));
        getContentPane().add(jButton75, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 230, 20, 20));
        getContentPane().add(jButton76, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 230, 20, 20));
        getContentPane().add(jButton77, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 20, 20));
        getContentPane().add(jButton78, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 20, 20));
        getContentPane().add(jButton79, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 190, 20, 20));
        getContentPane().add(jButton80, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, 20, 20));
        getContentPane().add(jButton81, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 210, 20, 20));
        getContentPane().add(jButton82, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, 20, 20));
        getContentPane().add(jButton83, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 210, 20, 20));
        getContentPane().add(jButton84, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 20, 20));
        getContentPane().add(jButton85, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 20, 20));
        getContentPane().add(jButton86, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 20, 20));
        getContentPane().add(jButton87, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 20, 20));
        getContentPane().add(jButton88, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 230, 20, 20));
        getContentPane().add(jButton89, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 20, 20));
        getContentPane().add(jButton90, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 20, 20));
        getContentPane().add(jButton91, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 20, 20));
        getContentPane().add(jButton92, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 20, 20));
        getContentPane().add(jButton93, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 20, 20));
        getContentPane().add(jButton94, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 20, 20));
        getContentPane().add(jButton95, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 20, 20));
        getContentPane().add(jButton96, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 20, 20));
        getContentPane().add(jButton97, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 20, 20));
        getContentPane().add(jButton98, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 20, 20));
        getContentPane().add(jButton99, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 20, 20));
        getContentPane().add(jButton100, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 20, 20));
        getContentPane().add(jButton101, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 20, 20));
        getContentPane().add(jButton102, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 20, 20));
        getContentPane().add(jButton103, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 20, 20));
        getContentPane().add(jButton104, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 20, 20));
        getContentPane().add(jButton105, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 20, 20));
        getContentPane().add(jButton106, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 20, 20));
        getContentPane().add(jButton107, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 20, 20));
        getContentPane().add(jButton108, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 20, 20));
        getContentPane().add(jButton109, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 20, 20));
        getContentPane().add(jButton110, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 20, 20));
        getContentPane().add(jButton111, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 20, 20));
        getContentPane().add(jButton112, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 20, 20));
        getContentPane().add(jButton113, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 200, 20, 20));
        getContentPane().add(jButton114, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 220, 20, 20));
        getContentPane().add(jButton115, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, 20, 20));
        getContentPane().add(jButton116, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, 20, 20));
        getContentPane().add(jButton117, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 20, 20));
        getContentPane().add(jButton118, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 20, 20));
        getContentPane().add(jButton119, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 20, 20));
        getContentPane().add(jButton120, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 20, 20));
        getContentPane().add(jButton121, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 20, 20));
        getContentPane().add(jButton122, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 20, 20));
        getContentPane().add(jButton123, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 20, 20));
        getContentPane().add(jButton124, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 20, 20));
        getContentPane().add(jButton125, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 20, 20));
        getContentPane().add(jButton126, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 20, 20));
        getContentPane().add(jButton127, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 20, 20));
        getContentPane().add(jButton128, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 20, 20));
        getContentPane().add(jButton129, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 20, 20));
        getContentPane().add(jButton130, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 20, 20));
        getContentPane().add(jButton131, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 20, 20));
        getContentPane().add(jButton132, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 20, 20));
        getContentPane().add(jButton133, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 20, 20));
        getContentPane().add(jButton134, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, 20, 20));
        getContentPane().add(jButton135, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 20, 20));
        getContentPane().add(jButton136, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 20, 20));
        getContentPane().add(jButton137, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 20, 20));
        getContentPane().add(jButton138, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 20, 20));
        getContentPane().add(jButton139, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 20, 20));
        getContentPane().add(jButton140, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 20, 20));
        getContentPane().add(jButton141, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 20, 20));
        getContentPane().add(jButton142, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 20, 20));
        getContentPane().add(jButton143, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 130, 20, 20));
        getContentPane().add(jButton144, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 150, 20, 20));
        getContentPane().add(jButton145, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 130, 20, 20));
        getContentPane().add(jButton146, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 150, 20, 20));
        getContentPane().add(jButton147, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 270, 20, 20));
        getContentPane().add(jButton148, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 290, 20, 20));
        getContentPane().add(jButton149, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 130, 20, 20));
        getContentPane().add(jButton150, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 150, 20, 20));
        getContentPane().add(jButton151, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 150, 20, 20));
        getContentPane().add(jButton152, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 130, 20, 20));
        getContentPane().add(jButton153, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 130, 20, 20));
        getContentPane().add(jButton154, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 150, 20, 20));
        getContentPane().add(jButton155, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 270, 20, 20));
        getContentPane().add(jButton156, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 290, 20, 20));
        getContentPane().add(jButton157, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 200, 20, 20));
        getContentPane().add(jButton158, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 220, 20, 20));
        getContentPane().add(jButton159, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 220, 20, 20));
        getContentPane().add(jButton160, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 200, 20, 20));
        getContentPane().add(jButton161, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 270, 20, 20));
        getContentPane().add(jButton162, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 290, 20, 20));
        getContentPane().add(jButton163, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 200, 20, 20));
        getContentPane().add(jButton164, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 220, 20, 20));
        getContentPane().add(jButton165, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 270, 20, 20));
        getContentPane().add(jButton166, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 290, 20, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logo mas chico.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/avion acientos.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelSeleccionAciento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelSeleccionAciento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelSeleccionAciento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelSeleccionAciento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelSeleccionAciento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton113;
    private javax.swing.JButton jButton114;
    private javax.swing.JButton jButton115;
    private javax.swing.JButton jButton116;
    private javax.swing.JButton jButton117;
    private javax.swing.JButton jButton118;
    private javax.swing.JButton jButton119;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton120;
    private javax.swing.JButton jButton121;
    private javax.swing.JButton jButton122;
    private javax.swing.JButton jButton123;
    private javax.swing.JButton jButton124;
    private javax.swing.JButton jButton125;
    private javax.swing.JButton jButton126;
    private javax.swing.JButton jButton127;
    private javax.swing.JButton jButton128;
    private javax.swing.JButton jButton129;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton130;
    private javax.swing.JButton jButton131;
    private javax.swing.JButton jButton132;
    private javax.swing.JButton jButton133;
    private javax.swing.JButton jButton134;
    private javax.swing.JButton jButton135;
    private javax.swing.JButton jButton136;
    private javax.swing.JButton jButton137;
    private javax.swing.JButton jButton138;
    private javax.swing.JButton jButton139;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton140;
    private javax.swing.JButton jButton141;
    private javax.swing.JButton jButton142;
    private javax.swing.JButton jButton143;
    private javax.swing.JButton jButton144;
    private javax.swing.JButton jButton145;
    private javax.swing.JButton jButton146;
    private javax.swing.JButton jButton147;
    private javax.swing.JButton jButton148;
    private javax.swing.JButton jButton149;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton150;
    private javax.swing.JButton jButton151;
    private javax.swing.JButton jButton152;
    private javax.swing.JButton jButton153;
    private javax.swing.JButton jButton154;
    private javax.swing.JButton jButton155;
    private javax.swing.JButton jButton156;
    private javax.swing.JButton jButton157;
    private javax.swing.JButton jButton158;
    private javax.swing.JButton jButton159;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton160;
    private javax.swing.JButton jButton161;
    private javax.swing.JButton jButton162;
    private javax.swing.JButton jButton163;
    private javax.swing.JButton jButton164;
    private javax.swing.JButton jButton165;
    private javax.swing.JButton jButton166;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
