/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author agust
 */
public class PanelSeleccionAciento extends javax.swing.JFrame {

    /**
     * Creates new form PanelSeleccionAciento
     */
    public PanelSeleccionAciento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        jButton102 = new javax.swing.JButton();
        jButton103 = new javax.swing.JButton();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton106 = new javax.swing.JButton();
        jButton107 = new javax.swing.JButton();
        jButton108 = new javax.swing.JButton();
        jButton109 = new javax.swing.JButton();
        jButton110 = new javax.swing.JButton();
        jButton111 = new javax.swing.JButton();
        jButton112 = new javax.swing.JButton();
        jButton113 = new javax.swing.JButton();
        jButton114 = new javax.swing.JButton();
        jButton121 = new javax.swing.JButton();
        jButton122 = new javax.swing.JButton();
        jButton123 = new javax.swing.JButton();
        jButton124 = new javax.swing.JButton();
        jButton125 = new javax.swing.JButton();
        jButton126 = new javax.swing.JButton();
        jButton143 = new javax.swing.JButton();
        jButton144 = new javax.swing.JButton();
        jButton145 = new javax.swing.JButton();
        jButton146 = new javax.swing.JButton();
        jButton147 = new javax.swing.JButton();
        jButton148 = new javax.swing.JButton();
        jButton149 = new javax.swing.JButton();
        jButton150 = new javax.swing.JButton();
        jButton151 = new javax.swing.JButton();
        jButton152 = new javax.swing.JButton();
        jButton153 = new javax.swing.JButton();
        jButton154 = new javax.swing.JButton();
        jButton155 = new javax.swing.JButton();
        jButton156 = new javax.swing.JButton();
        jButton157 = new javax.swing.JButton();
        jButton158 = new javax.swing.JButton();
        jButton159 = new javax.swing.JButton();
        jButton160 = new javax.swing.JButton();
        jButton161 = new javax.swing.JButton();
        jButton162 = new javax.swing.JButton();
        jButton163 = new javax.swing.JButton();
        jButton164 = new javax.swing.JButton();
        jButton165 = new javax.swing.JButton();
        jButton166 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton167 = new javax.swing.JButton();
        jButton168 = new javax.swing.JButton();
        jButton169 = new javax.swing.JButton();
        jButton170 = new javax.swing.JButton();
        jButton171 = new javax.swing.JButton();
        jButton172 = new javax.swing.JButton();
        jButton173 = new javax.swing.JButton();
        jButton174 = new javax.swing.JButton();
        jButton175 = new javax.swing.JButton();
        jButton176 = new javax.swing.JButton();
        jButton177 = new javax.swing.JButton();
        jButton178 = new javax.swing.JButton();
        jButton179 = new javax.swing.JButton();
        jButton180 = new javax.swing.JButton();
        jButton181 = new javax.swing.JButton();
        jButton182 = new javax.swing.JButton();
        jButton183 = new javax.swing.JButton();
        jButton184 = new javax.swing.JButton();
        jButton185 = new javax.swing.JButton();
        jButton186 = new javax.swing.JButton();
        jButton187 = new javax.swing.JButton();
        jButton188 = new javax.swing.JButton();
        jButton189 = new javax.swing.JButton();
        jButton190 = new javax.swing.JButton();
        jButton191 = new javax.swing.JButton();
        jButton192 = new javax.swing.JButton();
        jButton193 = new javax.swing.JButton();
        jButton194 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 240, 20, 20));
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 220, 20, 20));
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 20, 20));
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 20, 20));
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 20, 20));
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 20, 20));
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 20, 20));
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 20, 20));
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 20, 20));
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 20, 20));
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 150, 20, 20));
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 170, 20, 20));
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 20, 20));
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 20, 20));
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 20, 20));
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 20, 20));
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 20, 20));
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 20, 20));
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 20, 20));
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 20, 20));
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 20, 20));
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 20, 20));
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 20, 20));
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 20, 20));
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 20, 20));
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 20, 20));
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 20, 20));
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 20, 20));
        getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 20, 20));
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 20, 20));
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 20, 20));
        getContentPane().add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 20, 20));
        getContentPane().add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 20, 20));
        getContentPane().add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 20, 20));
        getContentPane().add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 20, 20));
        getContentPane().add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 20, 20));
        getContentPane().add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 20, 20));
        getContentPane().add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 20, 20));
        getContentPane().add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 20, 20));
        getContentPane().add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 20, 20));
        getContentPane().add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 20, 20));
        getContentPane().add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 20, 20));
        getContentPane().add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 20, 20));
        getContentPane().add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 20, 20));
        getContentPane().add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 20, 20));
        getContentPane().add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 20, 20));
        getContentPane().add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 20, 20));
        getContentPane().add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 20, 20));
        getContentPane().add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 20, 20));
        getContentPane().add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 20, 20));
        getContentPane().add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 220, 20, 20));
        getContentPane().add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, 20, 20));
        getContentPane().add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 20, 20));
        getContentPane().add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 20, 20));
        getContentPane().add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 100, 20, 20));
        getContentPane().add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 120, 20, 20));
        getContentPane().add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 220, 20, 20));
        getContentPane().add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 240, 20, 20));
        getContentPane().add(jButton65, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 20, 20));
        getContentPane().add(jButton66, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 190, 20, 20));
        getContentPane().add(jButton67, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 20, 20));
        getContentPane().add(jButton68, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 150, 20, 20));
        getContentPane().add(jButton69, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 170, 20, 20));
        getContentPane().add(jButton70, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 190, 20, 20));
        getContentPane().add(jButton71, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 20, 20));
        getContentPane().add(jButton72, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 150, 20, 20));
        getContentPane().add(jButton73, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 20, 20));
        getContentPane().add(jButton74, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 170, 20, 20));
        getContentPane().add(jButton75, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 190, 20, 20));
        getContentPane().add(jButton76, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 20, 20));
        getContentPane().add(jButton77, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 20, 20));
        getContentPane().add(jButton78, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 20, 20));
        getContentPane().add(jButton79, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 150, 20, 20));
        getContentPane().add(jButton80, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 20, 20));
        getContentPane().add(jButton81, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 20, 20));
        getContentPane().add(jButton82, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 190, 20, 20));
        getContentPane().add(jButton83, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 20, 20));
        getContentPane().add(jButton84, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 20, 20));
        getContentPane().add(jButton85, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 20, 20));
        getContentPane().add(jButton86, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 20, 20));
        getContentPane().add(jButton87, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 20, 20));
        getContentPane().add(jButton88, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, 20, 20));
        getContentPane().add(jButton89, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 20, 20));
        getContentPane().add(jButton90, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 20, 20));
        getContentPane().add(jButton91, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 20, 20));
        getContentPane().add(jButton92, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 20, 20));
        getContentPane().add(jButton93, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 20, 20));
        getContentPane().add(jButton94, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 20, 20));
        getContentPane().add(jButton95, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 20, 20));
        getContentPane().add(jButton96, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 20, 20));
        getContentPane().add(jButton97, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 20, 20));
        getContentPane().add(jButton98, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 20, 20));
        getContentPane().add(jButton99, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 20, 20));
        getContentPane().add(jButton100, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 20, 20));
        getContentPane().add(jButton101, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 20, 20));
        getContentPane().add(jButton102, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 20, 20));
        getContentPane().add(jButton103, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 20, 20));
        getContentPane().add(jButton104, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 20, 20));
        getContentPane().add(jButton105, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 20, 20));
        getContentPane().add(jButton106, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 20, 20));
        getContentPane().add(jButton107, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 20, 20));
        getContentPane().add(jButton108, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 20, 20));
        getContentPane().add(jButton109, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 20, 20));
        getContentPane().add(jButton110, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 20, 20));
        getContentPane().add(jButton111, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 20, 20));
        getContentPane().add(jButton112, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 20, 20));
        getContentPane().add(jButton113, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 160, 20, 20));
        getContentPane().add(jButton114, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 180, 20, 20));
        getContentPane().add(jButton121, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 20, 20));
        getContentPane().add(jButton122, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 20, 20));
        getContentPane().add(jButton123, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 20, 20));
        getContentPane().add(jButton124, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 20, 20));
        getContentPane().add(jButton125, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 20, 20));
        getContentPane().add(jButton126, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 20, 20));
        getContentPane().add(jButton143, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 100, 20, 20));
        getContentPane().add(jButton144, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 120, 20, 20));
        getContentPane().add(jButton145, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 100, 20, 20));
        getContentPane().add(jButton146, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 120, 20, 20));
        getContentPane().add(jButton147, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 220, 20, 20));
        getContentPane().add(jButton148, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 240, 20, 20));
        getContentPane().add(jButton149, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 100, 20, 20));
        getContentPane().add(jButton150, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 120, 20, 20));
        getContentPane().add(jButton151, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 120, 20, 20));
        getContentPane().add(jButton152, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 100, 20, 20));
        getContentPane().add(jButton153, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 100, 20, 20));
        getContentPane().add(jButton154, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 120, 20, 20));
        getContentPane().add(jButton155, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 220, 20, 20));
        getContentPane().add(jButton156, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 240, 20, 20));
        getContentPane().add(jButton157, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 160, 20, 20));
        getContentPane().add(jButton158, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 180, 20, 20));
        getContentPane().add(jButton159, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 180, 20, 20));
        getContentPane().add(jButton160, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 160, 20, 20));
        getContentPane().add(jButton161, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 220, 20, 20));
        getContentPane().add(jButton162, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 240, 20, 20));
        getContentPane().add(jButton163, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 160, 20, 20));
        getContentPane().add(jButton164, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 180, 20, 20));
        getContentPane().add(jButton165, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 220, 20, 20));
        getContentPane().add(jButton166, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 240, 20, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logo mas chico.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(jButton167, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 220, 20, 20));
        getContentPane().add(jButton168, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 20, 20));
        getContentPane().add(jButton169, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 20, 20));
        getContentPane().add(jButton170, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 20, 20));
        getContentPane().add(jButton171, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 20, 20));
        getContentPane().add(jButton172, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 20, 20));
        getContentPane().add(jButton173, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 20, 20));
        getContentPane().add(jButton174, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 20, 20));
        getContentPane().add(jButton175, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 20, 20));
        getContentPane().add(jButton176, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 20, 20));
        getContentPane().add(jButton177, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 20, 20));
        getContentPane().add(jButton178, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 20, 20));
        getContentPane().add(jButton179, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 20, 20));
        getContentPane().add(jButton180, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 20, 20));
        getContentPane().add(jButton181, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 20, 20));
        getContentPane().add(jButton182, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 20, 20));
        getContentPane().add(jButton183, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 20, 20));
        getContentPane().add(jButton184, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 20, 20));
        getContentPane().add(jButton185, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 20, 20));
        getContentPane().add(jButton186, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 20, 20));
        getContentPane().add(jButton187, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 20, 20));
        getContentPane().add(jButton188, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 20, 20));
        getContentPane().add(jButton189, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 20, 20));
        getContentPane().add(jButton190, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 20, 20));
        getContentPane().add(jButton191, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 20, 20));
        getContentPane().add(jButton192, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 20, 20));
        getContentPane().add(jButton193, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 20, 20));
        getContentPane().add(jButton194, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 20, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/avion acientos (1) (1) (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/avion acientos (1) (1) (1).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelSeleccionAciento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelSeleccionAciento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelSeleccionAciento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelSeleccionAciento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelSeleccionAciento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton113;
    private javax.swing.JButton jButton114;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton121;
    private javax.swing.JButton jButton122;
    private javax.swing.JButton jButton123;
    private javax.swing.JButton jButton124;
    private javax.swing.JButton jButton125;
    private javax.swing.JButton jButton126;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton143;
    private javax.swing.JButton jButton144;
    private javax.swing.JButton jButton145;
    private javax.swing.JButton jButton146;
    private javax.swing.JButton jButton147;
    private javax.swing.JButton jButton148;
    private javax.swing.JButton jButton149;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton150;
    private javax.swing.JButton jButton151;
    private javax.swing.JButton jButton152;
    private javax.swing.JButton jButton153;
    private javax.swing.JButton jButton154;
    private javax.swing.JButton jButton155;
    private javax.swing.JButton jButton156;
    private javax.swing.JButton jButton157;
    private javax.swing.JButton jButton158;
    private javax.swing.JButton jButton159;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton160;
    private javax.swing.JButton jButton161;
    private javax.swing.JButton jButton162;
    private javax.swing.JButton jButton163;
    private javax.swing.JButton jButton164;
    private javax.swing.JButton jButton165;
    private javax.swing.JButton jButton166;
    private javax.swing.JButton jButton167;
    private javax.swing.JButton jButton168;
    private javax.swing.JButton jButton169;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton170;
    private javax.swing.JButton jButton171;
    private javax.swing.JButton jButton172;
    private javax.swing.JButton jButton173;
    private javax.swing.JButton jButton174;
    private javax.swing.JButton jButton175;
    private javax.swing.JButton jButton176;
    private javax.swing.JButton jButton177;
    private javax.swing.JButton jButton178;
    private javax.swing.JButton jButton179;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton180;
    private javax.swing.JButton jButton181;
    private javax.swing.JButton jButton182;
    private javax.swing.JButton jButton183;
    private javax.swing.JButton jButton184;
    private javax.swing.JButton jButton185;
    private javax.swing.JButton jButton186;
    private javax.swing.JButton jButton187;
    private javax.swing.JButton jButton188;
    private javax.swing.JButton jButton189;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton190;
    private javax.swing.JButton jButton191;
    private javax.swing.JButton jButton192;
    private javax.swing.JButton jButton193;
    private javax.swing.JButton jButton194;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
