
package views;

import controllers.PerfilController;
import models.Usuario;
import models.dao.UsuarioDao;

public class PanelPerfil extends javax.swing.JFrame {

    public PanelPerfil(Usuario us) {
        initComponents();
        this.txtPassword.setVisible(false);
        this.txtPasswordConfirmada.setVisible(false);
        this.txtTelefono.setVisible(false);
        this.txtCodigo.setVisible(false);
        this.jSeparator1.setVisible(false);
        this.jSeparator2.setVisible(false);
        this.jSeparator3.setVisible(false);
        this.jSeparator4.setVisible(false);
        this.btnConfirmarCodigo.setVisible(false);
        this.btnConfirmarPassword.setVisible(false);
        this.txtTelefono.setVisible(false);
        this.btnConfirmarTelefono.setVisible(false);
        this.setLocationRelativeTo(null);
        UsuarioDao usDao = new UsuarioDao();
        PerfilController controller = new PerfilController(this, us, usDao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        btnVuelos = new javax.swing.JButton();
        btnReservas = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnConfirmarTelefono = new javax.swing.JButton();
        lblTelefono = new javax.swing.JLabel();
        lblNombreApellido = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        btnSeleccionarImagen = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCambiarPassword = new javax.swing.JButton();
        txtPasswordConfirmada = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        btnConfirmarPassword = new javax.swing.JButton();
        txtTelefono = new javax.swing.JTextField();
        btnConfirmarCodigo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtCodigo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnCambiarTelefono = new javax.swing.JButton();
        lblImagenPerfil = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logo mas chico.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 140));

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/menu.png"))); // NOI18N
        btnMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setDefaultCapable(false);
        btnMenu.setFocusPainted(false);
        btnMenu.setRequestFocusEnabled(false);
        btnMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/menu oscuro.png"))); // NOI18N
        btnMenu.setVerifyInputWhenFocusTarget(false);

        btnVuelos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/vuelos.png"))); // NOI18N
        btnVuelos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVuelos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVuelos.setDefaultCapable(false);
        btnVuelos.setFocusPainted(false);
        btnVuelos.setRequestFocusEnabled(false);
        btnVuelos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/vuelos oscuro.png"))); // NOI18N
        btnVuelos.setVerifyInputWhenFocusTarget(false);

        btnReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/reservas.png"))); // NOI18N
        btnReservas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnReservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReservas.setDefaultCapable(false);
        btnReservas.setFocusPainted(false);
        btnReservas.setRequestFocusEnabled(false);
        btnReservas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/reservas oscuro.png"))); // NOI18N
        btnReservas.setVerifyInputWhenFocusTarget(false);

        btnPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/pagos.png"))); // NOI18N
        btnPagos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPagos.setDefaultCapable(false);
        btnPagos.setFocusPainted(false);
        btnPagos.setRequestFocusEnabled(false);
        btnPagos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/pagos oscuro.png"))); // NOI18N
        btnPagos.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVuelos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReservas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPagos)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 720));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConfirmarTelefono.setBackground(new java.awt.Color(255, 204, 102));
        btnConfirmarTelefono.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnConfirmarTelefono.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirmarTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-confirmarTelefono.png"))); // NOI18N
        btnConfirmarTelefono.setBorder(null);
        btnConfirmarTelefono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarTelefono.setDefaultCapable(false);
        btnConfirmarTelefono.setFocusPainted(false);
        btnConfirmarTelefono.setRolloverEnabled(true);
        btnConfirmarTelefono.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-confirmarTelefono-h.png"))); // NOI18N
        btnConfirmarTelefono.setVerifyInputWhenFocusTarget(false);
        btnConfirmarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarTelefonoActionPerformed(evt);
            }
        });
        jPanel2.add(btnConfirmarTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, 180, 40));

        lblTelefono.setBackground(new java.awt.Color(51, 51, 51));
        lblTelefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(51, 51, 51));
        lblTelefono.setText("Teléfono");
        jPanel2.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 300, 31));

        lblNombreApellido.setBackground(new java.awt.Color(0, 0, 0));
        lblNombreApellido.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblNombreApellido.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreApellido.setText("Nombre y Apellido");
        jPanel2.add(lblNombreApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 300, 59));

        lblNombreUsuario.setBackground(new java.awt.Color(51, 51, 51));
        lblNombreUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblNombreUsuario.setText("Nombre de Usuario");
        jPanel2.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 300, 31));

        lblEmail.setBackground(new java.awt.Color(51, 51, 51));
        lblEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(51, 51, 51));
        lblEmail.setText("Email");
        jPanel2.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 300, 31));

        btnSeleccionarImagen.setBackground(new java.awt.Color(255, 204, 102));
        btnSeleccionarImagen.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnSeleccionarImagen.setForeground(new java.awt.Color(0, 0, 0));
        btnSeleccionarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-seleccionarImagen.png"))); // NOI18N
        btnSeleccionarImagen.setBorderPainted(false);
        btnSeleccionarImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeleccionarImagen.setDefaultCapable(false);
        btnSeleccionarImagen.setFocusPainted(false);
        btnSeleccionarImagen.setRequestFocusEnabled(false);
        btnSeleccionarImagen.setRolloverEnabled(true);
        btnSeleccionarImagen.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-seleccionarImagen-h.png"))); // NOI18N
        btnSeleccionarImagen.setVerifyInputWhenFocusTarget(false);
        btnSeleccionarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarImagenActionPerformed(evt);
            }
        });
        jPanel2.add(btnSeleccionarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 180, 40));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cambio de Teléfono");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 190, 40));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Cambio de Contraseña");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 190, 40));

        btnCambiarPassword.setBackground(new java.awt.Color(255, 204, 102));
        btnCambiarPassword.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCambiarPassword.setForeground(new java.awt.Color(0, 0, 0));
        btnCambiarPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-cambiarPassword.png"))); // NOI18N
        btnCambiarPassword.setBorderPainted(false);
        btnCambiarPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiarPassword.setDefaultCapable(false);
        btnCambiarPassword.setFocusPainted(false);
        btnCambiarPassword.setRequestFocusEnabled(false);
        btnCambiarPassword.setRolloverEnabled(true);
        btnCambiarPassword.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-cambiarPassword-h.png"))); // NOI18N
        btnCambiarPassword.setVerifyInputWhenFocusTarget(false);
        btnCambiarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(btnCambiarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 180, 40));

        txtPasswordConfirmada.setBackground(new java.awt.Color(204, 204, 204));
        txtPasswordConfirmada.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtPasswordConfirmada.setForeground(new java.awt.Color(51, 51, 51));
        txtPasswordConfirmada.setText("**********");
        txtPasswordConfirmada.setBorder(null);
        txtPasswordConfirmada.setDragEnabled(true);
        txtPasswordConfirmada.setFocusCycleRoot(true);
        jPanel2.add(txtPasswordConfirmada, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 180, -1));

        txtPassword.setBackground(new java.awt.Color(204, 204, 204));
        txtPassword.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtPassword.setText("**********");
        txtPassword.setBorder(null);
        txtPassword.setDragEnabled(true);
        txtPassword.setFocusCycleRoot(true);
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 180, -1));

        btnConfirmarPassword.setBackground(new java.awt.Color(255, 204, 102));
        btnConfirmarPassword.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnConfirmarPassword.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirmarPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-confirmarPasswordPerfil.png"))); // NOI18N
        btnConfirmarPassword.setBorderPainted(false);
        btnConfirmarPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarPassword.setDefaultCapable(false);
        btnConfirmarPassword.setFocusPainted(false);
        btnConfirmarPassword.setRequestFocusEnabled(false);
        btnConfirmarPassword.setRolloverEnabled(true);
        btnConfirmarPassword.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-confirmarPasswordPerfil-h.png"))); // NOI18N
        btnConfirmarPassword.setVerifyInputWhenFocusTarget(false);
        btnConfirmarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(btnConfirmarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 180, 40));

        txtTelefono.setBackground(new java.awt.Color(204, 204, 204));
        txtTelefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(51, 51, 51));
        txtTelefono.setText("Nuevo Teléfono");
        txtTelefono.setBorder(null);
        txtTelefono.setDragEnabled(true);
        txtTelefono.setFocusCycleRoot(true);
        txtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusLost(evt);
            }
        });
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 170, -1));

        btnConfirmarCodigo.setBackground(new java.awt.Color(255, 204, 102));
        btnConfirmarCodigo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnConfirmarCodigo.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirmarCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-confirmarCodigoPerfil.png"))); // NOI18N
        btnConfirmarCodigo.setBorderPainted(false);
        btnConfirmarCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarCodigo.setDefaultCapable(false);
        btnConfirmarCodigo.setFocusPainted(false);
        btnConfirmarCodigo.setRequestFocusEnabled(false);
        btnConfirmarCodigo.setRolloverEnabled(true);
        btnConfirmarCodigo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-confirmarCodigoPerfil-h.png"))); // NOI18N
        btnConfirmarCodigo.setVerifyInputWhenFocusTarget(false);
        btnConfirmarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCodigoActionPerformed(evt);
            }
        });
        jPanel2.add(btnConfirmarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 180, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 180, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 180, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 180, -1));

        txtCodigo.setBackground(new java.awt.Color(204, 204, 204));
        txtCodigo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(51, 51, 51));
        txtCodigo.setText("Código de verificación");
        txtCodigo.setBorder(null);
        txtCodigo.setDragEnabled(true);
        txtCodigo.setFocusCycleRoot(true);
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoFocusLost(evt);
            }
        });
        jPanel2.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 180, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 170, -1));

        btnCambiarTelefono.setBackground(new java.awt.Color(255, 204, 102));
        btnCambiarTelefono.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCambiarTelefono.setForeground(new java.awt.Color(0, 0, 0));
        btnCambiarTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-cambiarTelefono.png"))); // NOI18N
        btnCambiarTelefono.setBorderPainted(false);
        btnCambiarTelefono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiarTelefono.setDefaultCapable(false);
        btnCambiarTelefono.setFocusPainted(false);
        btnCambiarTelefono.setRequestFocusEnabled(false);
        btnCambiarTelefono.setRolloverEnabled(true);
        btnCambiarTelefono.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-cambiarTelefono-h.png"))); // NOI18N
        btnCambiarTelefono.setVerifyInputWhenFocusTarget(false);
        btnCambiarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarTelefonoActionPerformed(evt);
            }
        });
        jPanel2.add(btnCambiarTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 180, 40));

        lblImagenPerfil.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.add(lblImagenPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 170, 160));

        jPanel4.setBackground(new java.awt.Color(255, 204, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-eliminar.png"))); // NOI18N
        btnCerrar.setBorder(null);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setFocusPainted(false);
        btnCerrar.setRequestFocusEnabled(false);
        btnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-eliminar-h.png"))); // NOI18N
        btnCerrar.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 50, 50));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("FlyNow: Vuela fácil, vuela seguro.");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 280, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-encabezado.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 620, 720));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cambio de contraseña");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 190, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarTelefonoActionPerformed

    }//GEN-LAST:event_btnConfirmarTelefonoActionPerformed

    private void btnSeleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarImagenActionPerformed

    private void btnCambiarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarPasswordActionPerformed

    private void btnConfirmarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarPasswordActionPerformed

    private void txtTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusGained

    }//GEN-LAST:event_txtTelefonoFocusGained

    private void txtTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusLost

    }//GEN-LAST:event_txtTelefonoFocusLost

    private void btnConfirmarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarCodigoActionPerformed

    private void txtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoFocusGained

    private void txtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoFocusLost

    private void btnCambiarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarTelefonoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCambiarPassword;
    public javax.swing.JButton btnCambiarTelefono;
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnConfirmarCodigo;
    public javax.swing.JButton btnConfirmarPassword;
    public javax.swing.JButton btnConfirmarTelefono;
    public javax.swing.JButton btnMenu;
    public javax.swing.JButton btnPagos;
    public javax.swing.JButton btnReservas;
    public javax.swing.JButton btnSeleccionarImagen;
    public javax.swing.JButton btnVuelos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JSeparator jSeparator3;
    public javax.swing.JSeparator jSeparator4;
    public javax.swing.JLabel lblEmail;
    public javax.swing.JLabel lblImagenPerfil;
    public javax.swing.JLabel lblNombreApellido;
    public javax.swing.JLabel lblNombreUsuario;
    public javax.swing.JLabel lblTelefono;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JPasswordField txtPassword;
    public javax.swing.JPasswordField txtPasswordConfirmada;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
