
package views;

import controllers.NewPasswordController;
import models.Usuario;
import models.dao.UsuarioDao;

public class PanelNewPassword extends javax.swing.JFrame {

    public PanelNewPassword() {
        initComponents();
        this.setLocationRelativeTo(null);
        Usuario us = new Usuario();
        UsuarioDao usDao = new UsuarioDao();
        NewPasswordController controller = new NewPasswordController(this, us, usDao);
        this.btnConfirmarPassword.setVisible(false);
        this.btnConfirmarCodigo.setVisible(false);
        this.txtPassword.setVisible(false);
        this.txtCodigoVerificacion.setVisible(false);
        this.txtPasswordConfirmada.setVisible(false);
        this.jSeparator2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnConfirmarEmail = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnConfirmarPassword = new javax.swing.JButton();
        txtCodigoVerificacion = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtPasswordConfirmada = new javax.swing.JPasswordField();
        btnConfirmarCodigo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cambiar Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 430, -1));

        txtEmail.setBackground(new java.awt.Color(255, 204, 102));
        txtEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(51, 51, 51));
        txtEmail.setText("Nombre de Usuario o Email...");
        txtEmail.setBorder(null);
        txtEmail.setDragEnabled(true);
        txtEmail.setFocusCycleRoot(true);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 220, -1));

        btnConfirmarEmail.setBackground(new java.awt.Color(51, 51, 51));
        btnConfirmarEmail.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnConfirmarEmail.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-confirmarEmail.png"))); // NOI18N
        btnConfirmarEmail.setBorderPainted(false);
        btnConfirmarEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarEmail.setFocusPainted(false);
        btnConfirmarEmail.setRequestFocusEnabled(false);
        btnConfirmarEmail.setRolloverEnabled(true);
        btnConfirmarEmail.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-confirmarEmail-h.png"))); // NOI18N
        btnConfirmarEmail.setVerifyInputWhenFocusTarget(false);
        btnConfirmarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarEmailActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmarEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 220, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo mas chico.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 210, 150));

        btnConfirmarPassword.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnConfirmarPassword.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-confirmarPassword.png"))); // NOI18N
        btnConfirmarPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarPassword.setFocusPainted(false);
        btnConfirmarPassword.setRequestFocusEnabled(false);
        btnConfirmarPassword.setRolloverEnabled(true);
        btnConfirmarPassword.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-confirmarPassword-h.png"))); // NOI18N
        btnConfirmarPassword.setVerifyInputWhenFocusTarget(false);
        btnConfirmarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 220, 40));

        txtCodigoVerificacion.setBackground(new java.awt.Color(255, 204, 102));
        txtCodigoVerificacion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCodigoVerificacion.setForeground(new java.awt.Color(51, 51, 51));
        txtCodigoVerificacion.setText("Ingrese el código de verificación");
        txtCodigoVerificacion.setBorder(null);
        txtCodigoVerificacion.setDragEnabled(true);
        txtCodigoVerificacion.setFocusCycleRoot(true);
        jPanel1.add(txtCodigoVerificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 220, -1));

        txtPassword.setBackground(new java.awt.Color(255, 204, 102));
        txtPassword.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtPassword.setText("**********");
        txtPassword.setBorder(null);
        txtPassword.setDragEnabled(true);
        txtPassword.setFocusCycleRoot(true);
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 220, -1));

        txtPasswordConfirmada.setBackground(new java.awt.Color(255, 204, 102));
        txtPasswordConfirmada.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtPasswordConfirmada.setForeground(new java.awt.Color(51, 51, 51));
        txtPasswordConfirmada.setText("**********");
        txtPasswordConfirmada.setBorder(null);
        txtPasswordConfirmada.setDragEnabled(true);
        txtPasswordConfirmada.setFocusCycleRoot(true);
        jPanel1.add(txtPasswordConfirmada, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 220, -1));

        btnConfirmarCodigo.setBackground(new java.awt.Color(51, 51, 51));
        btnConfirmarCodigo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnConfirmarCodigo.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-confirmarCodigo.png"))); // NOI18N
        btnConfirmarCodigo.setBorderPainted(false);
        btnConfirmarCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarCodigo.setFocusPainted(false);
        btnConfirmarCodigo.setRequestFocusEnabled(false);
        btnConfirmarCodigo.setRolloverEnabled(true);
        btnConfirmarCodigo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-confirmarCodigo-h.png"))); // NOI18N
        btnConfirmarCodigo.setVerifyInputWhenFocusTarget(false);
        btnConfirmarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCodigoActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 220, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 220, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 220, -1));

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FlyNow: Vuela fácil, vuela seguro.");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 280, 50));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-eliminar.png"))); // NOI18N
        btnCerrar.setBorder(null);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setFocusPainted(false);
        btnCerrar.setRequestFocusEnabled(false);
        btnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-eliminar-h.png"))); // NOI18N
        btnCerrar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarEmailActionPerformed

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if (txtEmail.getText().equals("Ingrese Nueva Contraseña")) {
        txtEmail.setText("");
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if (txtEmail.getText().isEmpty()) {
        txtEmail.setText("Ingrese Nueva Contraseña");
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void btnConfirmarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarPasswordActionPerformed

    private void btnConfirmarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelNewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelNewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelNewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelNewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelNewPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnConfirmarCodigo;
    public javax.swing.JButton btnConfirmarEmail;
    public javax.swing.JButton btnConfirmarPassword;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField txtCodigoVerificacion;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JPasswordField txtPassword;
    public javax.swing.JPasswordField txtPasswordConfirmada;
    // End of variables declaration//GEN-END:variables
}
